TopLearn.Web/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TopLearn.Core.Security;
using TopLearn.Core.Services.Interfaces;
using TopLearn.Utility.Hasher;
using TopLearn.Utility.TextTools;
using TopLearn.ViewModel.UserViewModels;

namespace TopLearn.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : Controller
    {
        private IUserService _userService;
        private IRoleService _roleService;
        private IUserRepository _userRepository;
        private IPermissionService _permissionService;
        public UsersController(IUserService userService, IRoleService roleService,IUserRepository userRepository, IPermissionService permissionService)
        {
            _userService = userService;
            _roleService = roleService;
            _userRepository = userRepository;
            _permissionService = permissionService;
        }

        [Route("Admin/Users")]
        [PermissionChecker("AddUsers")]
        public IActionResult Index(int pageNumber = 1)
        {
            return View(GetUserInfo(pageNumber));
        }

        [HttpPost]
        [Route("Admin/Users")]
        [PermissionChecker("AddUsers")]
        public IActionResult Index([Bind("UserEmail,UserPassworld,roleId,PageNumber")] UserAdminPanelViewModel userAdminPanelViewModel)
        {
            string error = CheckUserInfo(userAdminPanelViewModel);
            if (!string.IsNullOrEmpty(error))
            {
                ModelState.AddModelError("UserEmail", error);
                return View(GetUserInfo(userAdminPanelViewModel.PageNumber));
            }
            var user = new DataLayer.Entities.User.User()
            {
                UserImage = "Defult.jpg",
                UserIsActive = true,
                UserEmailConfigurationCode = TextTools.GenerateUniqCode(),
                UserEmailConfigurationDateTime = DateTime.Now,
                UserDateTime = DateTime.Now,
                UserPassword = userAdminPanelViewModel.UserPassworld.ToEncodePasswordMd5(),
                UserEmail = userAdminPanelViewModel.UserEmail.TextFix(),
                UserLastUpdateDateTime = DateTime.Now,
                UserDescription = "ثبت نام توسط مدیر",
            };
            int userId = _userRepository.InsertUser(user);
            if (userId <= 0)
            {
                ModelState.AddModelError("UserEmail", "خطا در ثبت اطلاعات");
                return View(GetUserInfo(userAdminPanelViewModel.PageNumber));
            }
            _userRepository.InsertRolesToUser(userId, userAdminPanelViewModel.roleId);
            _userRepository.SaveUser();
            return View(GetUserInfo(userAdminPanelViewModel.PageNumber));


        }
        [HttpPost]
        [PermissionChecker("EditUsers")]
        public bool ActivateUser(int userId, string userEmail) {
            if (!userEmail.IsValidEmail()|| string.IsNullOrEmpty(userEmail)|| userId <= 0)
                return false;
            return _userService.ActivateUser(userId, userEmail, null,true);
        }
        [HttpPost]
        [PermissionChecker("EditUsers")]
        public bool InActiveUser(int userId, string userEmail,string description) {
            if (!userEmail.IsValidEmail()|| string.IsNullOrEmpty(description)|| string.IsNullOrEmpty(userEmail)|| userId <= 0)
                return false;
            return _userService.ActivateUser(userId, userEmail, description,false);
        }
        [HttpPost]
        [PermissionChecker("DeleteUsers")]
        public string DeleteUser(int userId) {
            if (!_userService.UserIsExist(userId))
                return "notfund";
            return _userRepository.DeleteUser(userId);
        }
        private UserAdminPanelViewModel GetUserInfo(int pageNumber = 1)
        {
            int skip = (pageNumber - 1) * 10;
            int userId = Convert.ToInt32(User.Identity.Name);
            UserAdminPanelViewModel userAdminPanelViewModel = new UserAdminPanelViewModel();
            userAdminPanelViewModel.UserModel = _userService.GetAllUser(skip, 10, userId, false);
            userAdminPanelViewModel.userInactiveViewModels = _userService.GetUsersInactive(skip, 10);
            userAdminPanelViewModel.UserInactiveCount = userAdminPanelViewModel.UserModel.Where(u => u.UserIsActive == false).Count();
            userAdminPanelViewModel.UserCount = userAdminPanelViewModel.UserModel.Count;
            userAdminPanelViewModel.roleViewModels = _roleService.GetAllRoles();
            userAdminPanelViewModel.PageNumber = pageNumber;
            userAdminPanelViewModel.isSubPermissionsAddUser = _permissionService.CheckPermission("AddUsers", userId);
            userAdminPanelViewModel.isSubPermissionsEditUser = _permissionService.CheckPermission("EditUsers", userId);
            userAdminPanelViewModel.isSubPermissionsDeleteUser = _permissionService.CheckPermission("DeleteUsers", userId);
            return userAdminPanelViewModel;
        }
        private string CheckUserInfo(UserAdminPanelViewModel userAdminPanelViewModel)
        {
            string error = null;
            if (!ModelState.IsValid)
            {
                error = "اطلاعات ارسالی صحیح نمی باشد";
                return error;

            }
            if (string.IsNullOrEmpty(userAdminPanelViewModel.UserEmail) || !(userAdminPanelViewModel.UserEmail.IsValidEmail()))
            {
                error = "ایمیل وارد شده معتبر نیست";
                return error;
            }
            if (userAdminPanelViewModel.roleId == null)
            {
                error = "نقش حتما باید برای کاربر انتخاب شود";
                return error;
            }    
            if (string.IsNullOrEmpty(userAdminPanelViewModel.UserPassworld))
            {
                error = "کلمه عبور معتبر نیست";
                return error;
            }
            if (userAdminPanelViewModel.UserPassworld.Length<6)
            {
                error = "طول کلمه عبور باید بیشتر از 6 کاراکتر باشد";
                return error;
            }
            return error;
        }
    }
}

TopLearn.Web/Areas/User/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TopLearn.Core.Services.Interfaces;
using TopLearn.Utility.Hasher;
using TopLearn.Utility.TextTools;
using TopLearn.Utility.Tools;
using TopLearn.ViewModel.UserViewModels;

namespace TopLearn.Web.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class ProfileController : Controller
    {

        private IUserService _userService;
        private IUserRepository _userRepository;
        public ProfileController(IUserService userService, IUserRepository userRepository)
        {
            _userService = userService;
            _userRepository = userRepository;
        }

        public IActionResult Index() => View(GetUserInfo());


        public async Task<IActionResult> EditProfile(UserEditProFileViewModel userEditProFileViewModel, IFormFile UserImage)
        {
            var user = _userService.GetUserById(userEditProFileViewModel.UserID);

            if (user == null)
            {
                ViewBag.error = "اطلاعات را درست وارد کنید";
                return View("Index", GetUserInfo());
            }

            if (user.UserName != user.UserName)
            {
                if (_userService.UserNameIsExist(userEditProFileViewModel.UserName))
                {
                    ViewBag.error = "این نام کاربری وجود دارد";
                    return View("Index", GetUserInfo());
                }
            }
            if (user.UserEmail != userEditProFileViewModel.UserEmail)
            {
                if (_userService.UserEmialIsExist(userEditProFileViewModel.UserEmail))
                {
                    ViewBag.error = "این  ایمیل وجود دارد";
                    return View("Index", GetUserInfo());
                }
            }

            if (userEditProFileViewModel.UserImage != null)
            {
                string imgName = TextTools.GenerateUniqCode() + Path.GetExtension(userEditProFileViewModel.UserImage.FileName); ;
                string a = Directory.GetCurrentDirectory();
                string upLoad = await ImageUploader.ImageUpload(a, "/wwwroot/PorojectImg/UserImage/", user.UserImage, imgName, userEditProFileViewModel.UserImage);
                if (upLoad != "1")
                {
                    ViewBag.error = "خطا در اپلود تصویر";
                    return View("Index", GetUserInfo());
                }
                user.UserImage = imgName;
            }


            #region Update
            user.UserName = userEditProFileViewModel.UserName;
            user.UserFristName = userEditProFileViewModel.UserFristName;
            user.UserLastName = userEditProFileViewModel.UserLastName;
            user.UserEmail = userEditProFileViewModel.UserEmail;
            user.UserAbout = userEditProFileViewModel.UserAbout;
            user.UserBirthday = userEditProFileViewModel.UserBirthday;
            _userRepository.UpdateUser(user);
            _userRepository.SaveUser();
            #endregion
            return View("Index", GetUserInfo());
        }


        public ActionResult ChangePassword(ChangePasswordViewModel changePasswordViewModel) {
            var user = _userService.GetUserById(changePasswordViewModel.UserId);

            if (user == null)
            {
                ViewBag.error = "اطلاعات را درست وارد کنید";
                return View("Index", GetUserInfo());
            }

            if (changePasswordViewModel.UserNewPassword != changePasswordViewModel.UserConfigortionNewPassword) {
                ViewBag.error = "کلمه عبور و تکرار آن مغایرت دارد";
                return View("Index", GetUserInfo());
            }

            if (changePasswordViewModel.UserNewPassword.Length < 6) {
                ViewBag.error = "کلمه عبور باید حداعقل 6 کاراکتر باشد";
                return View("Index", GetUserInfo());
            }

            if (user.UserPassword != changePasswordViewModel.UserOldPassWord.ToEncodePasswordMd5())
            {
                ViewBag.error = "کلمه عبور قبلی اشتباه است";
                return View("Index", GetUserInfo());
            }
        

            if (user.UserPassword == changePasswordViewModel.UserNewPassword.ToEncodePasswordMd5())
                return View("Index", GetUserInfo());
            user.UserPassword = changePasswordViewModel.UserNewPassword.ToEncodePasswordMd5();
            _userRepository.UpdateUser(user);
            _userRepository.SaveUser();
            return View("Index", GetUserInfo());
        }

        public UserinfoViewModel GetUserInfo()
        {


            UserinfoViewModel userinfoViewModel = new UserinfoViewModel();
            ChangePasswordViewModel changePasswordViewModel = new ChangePasswordViewModel();
            UserEditProFileViewModel userEditProFileViewModel = new UserEditProFileViewModel();
            UserViewModel userViewModel = new UserViewModel();
            var user = _userService.GetUserById(Convert.ToInt32(User.Identity.Name));
            #region UuserModel
            userViewModel.UserFristName = user.UserFristName;
            userViewModel.UserLastName = user.UserLastName;
            userViewModel.UserEmail = user.UserEmail;
            userViewModel.UserEmailConfigurationDateTime = user.UserEmailConfigurationDateTime;
            userViewModel.UserBirthday = user.UserBirthday;
            userViewModel.UserImage = user.UserImage;
            userViewModel.UserAbout = user.UserAbout;
            userViewModel.UserRol = _userService.GetUserRolesTitle(user.UserID);
            userViewModel.UserIsActive = user.UserIsActive;
            userViewModel.UserDateTime = user.UserDateTime;
            #endregion
            #region UuserEditProFileViewModel
            userEditProFileViewModel.UserID = user.UserID;
            userEditProFileViewModel.UserFristName = user.UserFristName;
            userEditProFileViewModel.UserLastName = user.UserLastName;
            userEditProFileViewModel.UserName = user.UserName;
            userEditProFileViewModel.UserAbout = user.UserAbout;
            userEditProFileViewModel.UserEmail = user.UserEmail;
            userEditProFileViewModel.UserBirthday = user.UserBirthday;
            #endregion

            changePasswordViewModel.UserId = user.UserID;

            userinfoViewModel.UserEditProFileViewModel = userEditProFileViewModel;
            userinfoViewModel.UserViewModel = userViewModel;
            userinfoViewModel.ChangePasswordViewModel = changePasswordViewModel;
            return userinfoViewModel;
        }

    }
}

TopLearn.Web/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> @ViewData["Title"] </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <partial name="_AdminStyle"/>

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <!-- Logo -->
            <a href="index.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini">پنل</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>کنترل پنل مدیریت</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="/Panel/images/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">افشین حیدری</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="/Panel/images/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        افشین حیدری
                                        <small>مدیریت کل سایت</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-right">
                                        <a asp-area="User" asp-controller="Profile" asp-action="Index" class="btn btn-info btn-flat">پروفایل</a>
                                    </div>
                                    <div class="pull-left">
                                        <a asp-controller="Account" asp-action="Logout" class="btn btn-danger btn-flat">خروج</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- right side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-right image">
                        <img src="/Panel/images/user2-160x160.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-right info">
                        <p>افشین حیدری</p>
                    </div>
                </div>
                <!-- search form -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="جستجو">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">منو</li>
                    <li>
                        <a href="index.html">
                            <i class="fa fa-dashboard"></i> <span>داشبرد</span>
                        </a>
                    </li> 
                    <li>
                        <a asp-area="Admin" asp-controller="Roles" asp-action="Index">
                            <i class="fa fa-dashboard"></i> <span>نقش ها و دسترسی ها</span>
                        </a>
                    </li>
                    <li>
                        <a href="widgets.html">
                            <i class="fas fa-store"></i><span>فروشگاه ها</span>
                            <span class="pull-left-container">
                                <small class="label pull-left bg-green">جدید</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="mailbox.html">
                            <i class="fas fa-shopping-cart"></i> <span>محصولات</span>
                            <span class="pull-left-container">
                                <small class="label pull-left bg-yellow">۱۲</small>
                                <small class="label pull-left bg-green">۱۶</small>
                                <small class="label pull-left bg-red">۵</small>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a asp-area="Admin" asp-controller="Users" asp-action="Index">
                            <i class="fas fa-users"></i> <span>کاربران</span>
                        </a>
                    </li>

                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @RenderBody()
        </div>
        <!-- /.content-wrapper -->
        <footer class="main-footer text-center">
            <strong>تمام حقوق برای <a href="#"> CMS </a> محفوظ است</strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <partial name="_AdminScript" />
    @RenderSection("Scripts", false)
</body>
</html>

TopLearn.Web/Areas/Admin/Views/Shared/_AdminScript.cshtml
<script src="/Panel/js/html5shiv.min.js"></script>
<script src="/Panel/js/respond.min.js"></script>
<!-- jQuery 3 -->
<script src="/Panel/js/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="/Panel/js/bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="/Panel/js/adminlte.js"></script>
<!-- ChartJS -->
@*<script src="/Panel/js/Chart.js"></script>*@
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
@*<script src="/Panel/js/dashboard.js"></script>*@
<!--CMS custom script-->
<script src="~/js/jquery.validate.min.js"></script>

<script src="~/js/jquery.validate.unobtrusive.min.js"></script>

<script src="/Panel/js/script.js"></script>

TopLearn.Web/Areas/Admin/Views/Shared/_AdminStyle.cshtml
    <!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="/Panel/css/bootstrap-theme.css">
<!-- Bootstrap rtl -->
<link rel="stylesheet" href="/Panel/css/rtl.css">
<!-- Font Awesome -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
      integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<link rel="stylesheet" href="/Panel/css/font-awesome.min.css">
<!-- Theme style -->
<link rel="stylesheet" href="/Panel/css/AdminLTE.css">
<link rel="stylesheet" href="/Panel/css/Admin.css">
<!-- AdminLTE Skins. Choose a skin from the /Panel/css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="/Panel/css/_all-skins.min.css">
<!--CMS custom style-->
<link rel="stylesheet" href="/Panel/css/style.css">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->